let start=document.querySelector("h1");
setTimeout(()=>{
    start.innerText="9";
    setTimeout(()=>{
        start.innerText="8";
        setTimeout(()=>{
            start.innerText="7";
            setTimeout(()=>{
                start.innerText="6";
                setTimeout(()=>{
                    start.innerText="5";
                    setTimeout(()=>{
                        start.innerText="4";
                        setTimeout(()=>{
                            start.innerText="3";
                            setTimeout(()=>{
                                start.innerText="2";
                                setTimeout(()=>{
                                    start.innerText="1";
                                    setTimeout(()=>{
                                        start.innerText="Happy Independence Day🎉🎊";
                                    },1000)
                                },1000)
                            },1000)
                        },1000)
                    },1000)
                },1000)
            },1000)
        },1000)
    },1000)
},1000)